### ISSUE TITLE
timeout transition group TICK doesn't trigger animation in Safari?

### ISSUE THREAD

**Issue by noahgrant** [Khan/react-components#40]
Hi,

Have you noticed that the TICK of 17 ms in timeout transition group doesn't seem to be enough to trigger an animation in Safari (desktop or mobile)?  Seems to work great in everything else.

Thanks!

Noah

**Comment by idw111** [comment]
I'm experiencing the same issue.
Safari does not seem to work properly with TimeoutTransitionGroup.

**Comment by devgeeks** [comment]
:+1: 

I also appear to be seeing this... not sure if it has always been true or only recently.

**Comment by devgeeks** [comment]
Found this issue on ReactCSSTransitionGroup

https://github.com/facebook/react/issues/2104

I tried it, and moving the `transition` CSS from `enter` to `enter-active` fixes this issue on Safari.

**Comment by noahgrant** [comment]
wow, that worked for me, too.  i should add that i also had to _remove_ the transition from `enter`, not just add it to `enter-active` (i had tried adding it to both, which didn't work). i'll close this, though it'd be nice if the interface mirrored `CSSTransitionGroup` (minus the timeouts, of course).

**Comment by spicyj** [comment]
@noahgrant Sorry, what would you like changed here?
