### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by dmfilipenko** [Khan/react-components#48]
Please, update npm version. 
When I'm installing react-components through npm i've got this code
`var $ = require('jquery');` in timeout-transition-group

**Comment by dmfilipenko** [comment]
@jeresig please, look on this

**Comment by christopherscott** [comment]
+1; pointing to github #master for now

**Comment by xymostech** [comment]
I just pushed a new version 0.3.0 to npm, hopefully that works for you! I'm also going to update react-components to use react 0.14.0 in a bit, and release that as 0.4.0.
