### ISSUE TITLE
Implementing "appear" in timeout transition group

### ISSUE THREAD

**Issue by johnmanong** [Khan/react-components#49]
Hey guys,

Have you thought about adding the transitionAppear functionality to timeout-transition-group.jsx? Happy to send a PR if your interested.

**Comment by spicyj** [comment]
As of React 0.14 you can (and should) specify timeouts directly on CSSTransitionGroup so TimeoutTransitionGroup isn't needed.

**Comment by johnmanong** [comment]
Is that component considered deprecated then?

In our case, we aren't ready to update to 14 and are using timeout groups.

On Friday, November 13, 2015, Ben Alpert <notifications@github.com> wrote:

> Closed #49 <https://github.com/Khan/react-components/issues/49>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/react-components/issues/49#event-464261747>.
>


-- 
Best,
John Ong

**Comment by johnmanong** [comment]
@spicyj ?

**Comment by ariabuckles** [comment]
@johnmanong yes, I'd consider this component deprecated. If you want to add `transitionAppear` to a fork and use that because you're on on React 0.14 yet, go for it! But that probably won't be merged upstream <3.

**Comment by johnmanong** [comment]
Sounds good! Thanks for the update!!

On Monday, November 16, 2015, Aria Buckles <notifications@github.com> wrote:

> @johnmanong <https://github.com/johnmanong> yes, I'd consider this
> component deprecated. If you want to add transitionAppear to a fork and
> use that because you're on on React 0.14 yet, go for it! But that probably
> won't be merged upstream <3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/react-components/issues/49#issuecomment-157149144>
> .
>


-- 
Best,
John Ong
