### ISSUE TITLE
Rendering in Chromium browsers

### ISSUE THREAD

**Issue by MovGP0** [Khan/react-components#63]
I am unsure if this is the proper location to report this, but the Khan Academy website doesn't render properly in Chromium based browsers, like Chrome and Opera. 

![khan academy in chrome](https://cloud.githubusercontent.com/assets/83339/25105577/85482342-23c5-11e7-91a3-72cf03f05531.png)

Internet Explorer, Edge, and Firefox render everything properly.

**Comment by xymostech** [comment]
Hi @MovGP0. Thanks for letting us know, but this isn't the right place to report this. There's a button at the bottom right of the exercise that says "Report a mistake in this question" that you can use to report a problem, or report your bug at https://khanacademy.zendesk.com/hc/en-us
