### ISSUE TITLE
TeX support for react native 

### ISSUE THREAD

**Issue by karan101292** [Khan/react-components#64]
Is it possible to use TeX component in react native. TeX requires react native and I guess react native does not support dom

**Comment by kevinbarabash** [comment]
@karan101292 it's not possible to use the TeX component with React Native for that exact reason, there's no DOM.

**Comment by kevinbarabash** [comment]
That being said, there may be some way to use this component inside a React Native `WebView`.

**Comment by karan101292** [comment]
Okay thanks
